### ISSUE TITLE
Auto processes start from task scheduler.

### ISSUE THREAD

**Issue by kblair1** [interlark/ustvgo-iptv#29] opened 2022-07-18 18:15 UTC
Need switch setting or config setting to start processes running after server reboot and starting app with task scheduler.

**Comment by interlark** [comment] 2022-07-18 18:19
Why not to use one of these?

1. crontab
2. rc.local
3. init.d
4. systemd

**Comment by interlark** [comment] 2022-07-18 19:08
1. Create systemd service file
```bash
sudo nano /etc/systemd/system/ustvgo.service
```

```ini
[Unit]
Description=USTVGO Free IPTV.
After=network.target

[Service]
User=USERNAME
Type=notify
Restart=always
ExecStart=/home/USERNAME/.local/bin/ustvgo-iptv

[Install]
WantedBy=multi-user.target
```

2. Set permissions and enable the service
```bash
sudo chmod 644 /etc/systemd/system/ustvgo.service
sudo systemctl enable ustvgo.service
```

3. Reboot

Don't forget to replace `USERNAME` with your actual username.

**Comment by interlark** [comment] 2022-07-19 07:37
[Added](https://github.com/interlark/ustvgo-iptv/commit/fb14b6014c03086ae6463ac7adef336f78f59b75) "Autostart" section to the [readme](https://github.com/interlark/ustvgo-iptv/blob/master/README.md). The issue is closed as I suppose it's solved.

**Closed by interlark** 2022-07-19 07:37 UTC
